version: '3.8'

services:
  consyn-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: consyn-ai/api:latest
    container_name: consyn-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - MODEL_DIR=/app/models
      - DATA_DIR=/app/data
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - MODELS_TO_PRELOAD=verse
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    command: ["uvicorn", "consyn.api.main:app", "--host", "0.0.0.0", "--port", "8000"]

  consyn-ui:
    image: nginx:alpine
    container_name: consyn-ui
    ports:
      - "80:80"
    volumes:
      - ./ui:/usr/share/nginx/html
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - consyn-api
    restart: unless-stopped

  # Uncomment to enable monitoring with Prometheus and Grafana
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./deployment/prometheus:/etc/prometheus
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #     - '--web.console.templates=/usr/share/prometheus/consoles'
  #   restart: unless-stopped

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./deployment/grafana/provisioning:/etc/grafana/provisioning
  #     - grafana_data:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=consyn
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   depends_on:
  #     - prometheus
  #   restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data: